# code: language=ansible
---
- name: Restart wireguard
  when: ansible_facts['service_mgr'] == "openrc"
  become: true
  ansible.builtin.service:
    name: "wireguard_{{ wireguard_client_iface_name }}"
    state: restarted

- name: Restart wireguard
  when: ansible_facts['service_mgr'] == "systemd"
  become: true
  ansible.builtin.systemd_service:
    name: "wg-quick@{{ wireguard_client_iface_name }}"
    state: restarted
